version: '3.0'
services:
  prometheus:
    image: localhost:5000/base/prometheus
    ports:
    - "9090:9090"
    links:
    - app
  app:
    image: localhost:5000/base/app
	volumes:
	  - /opt/wildfly/standalone/log:/opt/wildfly-14.0.1.Final/standalone/log
    - /opt/wildfly/standalone/deployments:/opt/wildfly-14.0.1.Final/standalone/deployments
    - /opt/wildfly/standalone/configuration:/opt/wildfly-14.0.1.Final/standalone/configuration
  env_file: metrics.env
  user: serveradmin:serveradmin
  command: bash -c "/opt/jboss/wildfly/bin/standalone.sh -c standalone-full.xml -b 0.0.0.0 -bmanagement 0.0.0.0"
  ports: 
	  - "8282:8080"
networks:
  default:
    external:
      name: proxy_net
	