global:
  scrape_interval:     15s

  external_labels:
    monitor: 'caas-monitor'

scrape_configs:
- job_name: 'caas-metrics'
    scrape_interval: 5s
    metrics_path: '/caas/resources/metrics/'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: "prometheus"
	dns_sd_configs:
    - names:
      - 'localhost'
      type: 'A'
      port: 443