global:
  scrape_interval:     15s

  external_labels:
    monitor: 'caas-monitor'

scrape_configs:
  - job_name: 'caas-metrics'
    scrape_interval: 5s
    metrics_path: '/caas/resources/metrics/'
    static_configs:
- targets: ['caas:8080']